name: biosync
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  syncfusion_flutter_charts: ^20.4.44
  google_fonts: ^5.1.0
  flutter_animate: ^4.2.0
  glassmorphism: ^3.0.0 
  speech_to_text: ^6.1.1
  flutter_tts: ^3.7.0
  http: ^1.1.0
  flutter_svg: ^2.0.9
  provider: ^6.1.1
  fluttertoast: ^8.2.4
  shared_preferences: ^2.2.0
  intl: ^0.18.1
  web_socket_channel: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
